### PR TITLE
chore: Add v1 APIs and Conversion webhooks for v0.34.x

### PR DESCRIPTION
**Pull request by engedaam**
Fixes #N/A 

**Description**
- Add v1 APIs and the conversion webhooks
- This is a copy and from main to release a patch version of 0.34

**How was this change tested?**
- `make presubmit`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by engedaam — COMMENTED** [review]
/karpenter snapshot

**Review by engedaam — COMMENTED** [review]
/karpenter snapshot

**Review by engedaam — COMMENTED** [review]
/karpenter snapshot

**Review by engedaam — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — DISMISSED** [review]
LGTM 🚀

**Review by njtran — APPROVED** [review]

**Pull request merged**
