### PR TITLE
chore: Remove finalizer with `Update()` instead of `Patch()`

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #N/A 

**Description**

`Update()` operations to the finalizer allow us to avoid the errors that were mentioned in https://github.com/kubernetes-sigs/karpenter/pull/1086 around strategic merge patching. This is the better alternative compared to `Patch()`, since it allows us to do optimistic locking and avoid spurious errors in Karpenter for adding finalizers due to list replacement on JSON merge patching. `removing termination finalizer, NodeClaim.karpenter.sh \"slothboulder-2-etpuq1of8e-bnllc\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"foregroundDeletion\"}"}`

**How was this change tested?**

`make presubmit`
`/karpenter snapshot`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by engedaam — DISMISSED** [review]
LGTM 🚀

**Review by engedaam — APPROVED** [review]
LGTM 🚀

**Pull request merged**
