### PR TITLE
test PR - do not merge: 6+ minute delay fix with CI

### PR DESCRIPTION
**Pull request by AndrewSirenko**
Fixes #N/A 

**Description**

Real PR [test: Ensure no 6+ minute delays for disrupted stateful workloads](https://github.com/aws/karpenter-provider-aws/pull/6484)

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by njtran — COMMENTED** [review]
/karpenter snapshot

**Review by engedaam — COMMENTED** [review]
/karpenter snapshot

**Review by njtran — COMMENTED** [review]
/karpenter snapshot

**Review by engedaam — COMMENTED** [review]
/karpenter snapshot

**Comment by AndrewSirenko** [comment]
/karpenter snapshot

/shrug

I tried ¯\\_(ツ)_/¯

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by njtran — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by njtran — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Comment by AndrewSirenko** [comment]
Looks like karpenter version in go mod changed, and my replace directive didn't refer to correct version, fixed now.

**Pull request closed without merging**
