### PR TITLE
chore: Update usage of `aws/karpenter` throughout the repo

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #N/A 

**Description**

This PR updates the usage of `aws/karpenter` to be `aws/karpenter-provider-aws` throughout the repository, in documentation, and as a blocker on Github Actions.

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by engedaam — APPROVED** [review]
LGTM 🚀

**Pull request merged**
