### PR TITLE
chore: Replace ratelimiters with those from awslabs/operatorpkg

### PR DESCRIPTION
**Pull request by rschalo**
Fixes #N/A 

**Description**
Utilizes https://github.com/awslabs/operatorpkg/blob/main/reasonable/reasonable.go
**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — DISMISSED** [review]
LGTM 🚀

**Review by ellistarn — APPROVED** [review]
Nice!

**Review by jonathan-innis — DISMISSED** [review]
LGTM 🚀

**Review by jonathan-innis — APPROVED** [review]
LGTM :Rockte

**Pull request merged**
