### PR TITLE
feat(chart): Added cosign verify docs

### PR DESCRIPTION
**Pull request by stevehipwell**
Fixes #N/A 

**Description**
This PR adds documentation on how to use `cosign` to verify the Karpenter Helm chart.

**How was this change tested?**
By following the documentation along for the `0.35.0` Helm chart which has been signed.

**Does this change impact docs?**
- [x] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@jonathan-innis hopefully these are the docs that you requested?

**Review by jonathan-innis — APPROVED** [review]
Nice! I think that this could also be useful in the v0.35.0 docs as well! Up to you if you think that we should update them now or can wait for the v0.36.0 release to put them out there

**Comment by stevehipwell** [comment]
@jonathan-innis I'm not sure I'd worry about getting this into the docs outside of a general release.

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Pull request merged**
