### PR TITLE
feat: support unknown resources

### PR DESCRIPTION
**Pull request by universam1**
**Description**

depends on https://github.com/aws/karpenter-core/pull/603 - please follow this issue

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by universam1** [comment]
bump

**Comment by johngmyers** [comment]
@universam1 could you fix the CI failures?

**Comment by universam1** [comment]
> @universam1 could you fix the CI failures?

@johngmyers Thanks for the reply - the changes in core https://github.com/aws/karpenter-core/pull/603 need to be merged first for this repo ci to pass. How can we attack this?

**Comment by universam1** [comment]
bump

**Comment by jonathan-innis** [comment]
@universam1 Looks like this PR still depends on the PR over in `kubernetes-sigs/karpenter`. Looks like from the initial discussion that it would be good for you to come to WG next Monday 9am PST since this problem is complex and we could discuss more there: https://github.com/kubernetes-sigs/karpenter/pull/603#issuecomment-1788108586.

**Comment by jonathan-innis** [comment]
We're going to close out this PR for now to make sure we are just maintaining active PRs in our backlog. Given the fact that we are having discussion in https://github.com/kubernetes-sigs/karpenter/pull/603#issuecomment-1788108586 and in https://github.com/kubernetes-sigs/karpenter/issues/751, I think we need to come to some resolution in how we handle this problem generically before we come to specific solutions in the cloud provider code.

**Pull request closed without merging**
