### PR TITLE
fix: cherry-pick local zone fix to v0.32.x

### PR DESCRIPTION
**Pull request by jmdeal**
Fixes #N/A 

**Description**
Cherry-picks the following commits into release v0.32.4:
- https://github.com/aws/karpenter-provider-aws/pull/5308

**How was this change tested?**
N/A

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Comment by jonathan-innis** [comment]
I think we need to cherry-pick over the change that updated the way that we push our Snapshots first; otherwise, this isn't going to work running in the context of main

**Comment by jmdeal** [comment]
> I think we need to cherry-pick over the change that updated the way that we push our Snapshots first; otherwise, this isn't going to work running in the context of main

Yep, I actually just needed to build and publish the snapshot, didn't need to e2e tests to run.

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Pull request merged**
