### PR TITLE
feat: add cpu sustained clock speed label to instance metadata

### PR DESCRIPTION
**Pull request by aidan-canva**
**Description**
Some workloads are sensitive to variations instance CPU clock speed - either preferring a specific threshold or at least ensuring consistency across replicas.  This PR adds the EC2 `SustainedClockSpeedInGhz` value as a Karpenter label (`karpenter.k8s.aws/instance-cpu-sustained-clock-speed-mhz`) so that workloads can add their preference.

The upstream value from the EC2 API is in Ghz and represented as a float (ie 2.4).  nodeSelectors only support ints or strings and most use-cases for this will want to leverage the `Gt` or `Lt` operators to set minimum/maximum values.  To make this usable, this implementation converts the Ghz value into Mhz and represents it as an int.

**How was this change tested?**
- `make test`
- Local deployment / manual testing

**Does this change impact docs?**
Do codegen docs count? `website/content/en/preview/reference/instance-types.md` has been updated to reflect this new instance attribute.

- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rschalo** [comment]
Thanks for your contribution! Running the test workflows.

**Comment by njtran** [comment]
@aidan-canva are you able to fix the CI errors?

**Comment by aidan-canva** [comment]
@njtran apologies for the delay, I've been on vacation for a period.  I've just pushed a fix which should hopefully address the CI failures.  Can I kick checks off myself?

**Comment by anteliano** [comment]
Without this feature it is very tricky to avoid the slow instance types like m5a which is 2.5Ghz while seemingly similar m5 is on 3.1Ghz, the difference is significant for many workloads.

**Comment by aidan-canva** [comment]
I'm still motivated to get this PR merged - I believe it was in a mergable stable 3 weeks ago and just waiting for a repo owner to trigger the CI checks.  Since then, there are now some merge conflicts that need to be resolved (I can do that) - but it seems wasteful to do it and not get an indication someone can help get this merged.

**Comment by rschalo** [comment]
Hi @aidan-canva, apologies for the delay and timing. We're working on the next minor right now, think you could have this ready for review by Thursday morning and targeting merge Thursday EOD? Also, mind removing the instance type generation from the diff for this PR? We can do a fast-follow PR.

**Comment by aidan-canva** [comment]
> Hi @aidan-canva, apologies for the delay and timing. We're working on the next minor right now, think you could have this ready for review by Thursday morning and targeting merge Thursday EOD? Also, mind removing the instance type generation from the diff for this PR? We can do a fast-follow PR.

@rschalo - No worries, I appreciate its a hectic time of year for most of AWS! 

I've just merged `main` and cleaned up some merge conflicts and validated this is passing tests via `make test`.  I've also reset `website/content/en/preview/reference/instance-types.md` back to `main` to avoid further drift/conflicts.

Should be ready for a CI run now.

**Review by rschalo — COMMENTED** [review]
/karpenter snapshot

**Comment by aidan-canva** [comment]
> Two tests failling from snapshot:
> 
> * `[It] should delete pod with do-not-disrupt when it reaches its terminationGracePeriodSeconds` which passes locally so appears to be a flake.
> * `[It] should provision nodes for a deployment that requests vpc.amazonaws.com/pod-eni (security groups for pods)` also seems to be a flake based on the instance type it launches. Will verify again in AM PST.

I looked at a few recently merged PR's and some of them also have these tests failing.  Looks like a flake like you suggested.

**Review by rschalo — APPROVED** [review]
LGTM. We'll need a fast-follow for the instance types and scheduling docs. Thanks again for the contribution!

**Pull request merged**
