### PR TITLE
feat(crd): add optional custom annotations to the crds

### PR DESCRIPTION
**Pull request by victor-keltio**
Fixes #N/A 

**Description**

add an option in the value file to set custom annotations specificly to tthe custom resource definitions
so we can set in our use case the helm keep tag to ensure the crds never get deleted by an accidental uninstall

```yaml
  annotations:
    helm.sh/resource-policy: keep
```

**How was this change tested?**

`helm template`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

This is the same as #6655 that is closed.

### CODE REVIEW

**Review by jonathan-innis — DISMISSED** [review]
LGTM 🚀

**Comment by jonathan-innis** [comment]
@victor-keltio Approved, but it seems like CI is failing :(

**Comment by victor-keltio** [comment]
Hey @jonathan-innis, I just fixed the issue (`sponge` was not found) by using the _old but gold_ `> $i.new && mv $i.new $i` instead

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Pull request merged**
