### PR TITLE
ci: Fix oras ArtifactHub config push

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #N/A 

**Description**

Fix pushing the `artifacthub-repo.yaml` file

**How was this change tested?**

`/karpenter snapshot`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/Karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jigisha620 — APPROVED** [review]
LGTM

**Pull request merged**
