### PR TITLE
feat(chart): expose health port via svc

### PR DESCRIPTION
**Pull request by owais-maswala**
**Description**

Expose health port via Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: karpenter
  namespace: dev
  labels:
    helm.sh/chart: karpenter-0.36.0
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/version: "0.36.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
    - name: http-metrics
      port: 8000
      targetPort: http-metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/instance: karpenter
```

tested on k8s cluster, allows reaching `karpenter.dev.svc.cluster.local:8081/healthz`

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by engedaam — APPROVED** [review]
LGTM 🚀

**Comment by ellistarn** [comment]
What use case does this meet? It's a bit odd to me that we would loadbalance a health port.

**Comment by owais-maswala** [comment]
> What use case does this meet? It's a bit odd to me that we would loadbalance a health port.

I'd like to monitor the health/availability of Karpenter using the Blackbox Exporter/Prometheus Probes

**Comment by ellistarn** [comment]
Is it not possible to scrape the pods directly?

**Comment by owais-maswala** [comment]
> Is it not possible to scrape the pods directly?

Sure its possible, but pods are ephemeral, and would involve using Endpoints to dynamically update our Probe config at regular intervals

Probing the Service instead allows for a stable endpoint and abstraction away from individual pods. I am setting up SLO's as opposed to alerting (which we already have at a pod level)

We have the same setup for 20+ other services on our clusters, but Karpenter is the exception as it does not currently have its health port exposed via the Service

**Comment by jonathan-innis** [comment]
> It's a bit odd to me that we would loadbalance a health port

**Pull request closed without merging**
