### PR TITLE
feat: allow setting service annotations via helm chart

### PR DESCRIPTION
**Pull request by jamesduffy**
Fixes #N/A 

**Description**
Allows setting annotations on the karpenter service. We need this so that we can add annotations to setup datadog to monitor karpenter. There are probably other use cases.

**How was this change tested?**

Generated a helm chart locally with the additional values:

```yaml
service:
  annotations:
    ad.datadoghq.com/service.checks: |
      {
        "karpenter": {
          "cluster_check": true,
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:8000/metrics",
              "exclude_metrics": [
                "^karpenter\\.go\\..*$"
              ]
            }
          ]
        }
      }
```

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jmdeal** [comment]
What's preventing you from using the existing `additionalAnnotations` field? Unless absolutely necessary, we'd like to avoid additional configuration in the helm chart.

**Comment by jamesduffy** [comment]
> What's preventing you from using the existing `additionalAnnotations` field? Unless absolutely necessary, we'd like to avoid additional configuration in the helm chart.

`additionalAnnotations` adds the annotations to a lot of different things. This would be picked up from the Datadog agent as separate checks and instead of running just one check for Karpenter it would run duplicate checks for each place `additionalAnnotations` is injected. Therefore, we would need a way to add the annotation in a single place. Datadog annotations are often on the service.

**Comment by jamesduffy** [comment]
@jmdeal I would like to move forward with this if my explanation makes sense.

**Comment by jmdeal** [comment]
Sorry this has slipped, could you elaborate on what the consequences of this are?

> This would be picked up from the Datadog agent as separate checks and instead of running just one check for Karpenter it would run duplicate checks for each place additionalAnnotations is injected.

Unless this is strictly blocking, and no other workarounds exist, we don't want to expand the configuration surface for the helm chart we ship.

**Comment by jamesduffy** [comment]
> Sorry this has slipped, could you elaborate on what the consequences of this are?
> 
> > This would be picked up from the Datadog agent as separate checks and instead of running just one check for Karpenter it would run duplicate checks for each place additionalAnnotations is injected.
> 
> Unless this is strictly blocking, and no other workarounds exist, we don't want to expand the configuration surface for the helm chart we ship. 

The datadog agent watches for annotations to configure it's checks/metric collection. Using the existing additionalAnnotations would create annotations on more than one resource. This would configure the datadog agent to run multiple collections of the same metrics making it unusable.

**Comment by jmdeal** [comment]
Got it, I assume for most resources this would be a no-op, but you can get duplicate metrics since it would scrape both the Karpenter pods and the service?

**Comment by jamesduffy** [comment]
Correct.

**Review by jmdeal — APPROVED** [review]
Discussed offline with other team members, the use-case seems strong enough. LGTM 🚀

**Pull request merged**
