### PR TITLE
feat: Reduce hop token count

### PR DESCRIPTION
**Pull request by rschalo**
Fixes #N/A 

**Description**
Disables IMDS access from pods by reducing hop limit to 1

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — APPROVED** [review]
Is there any testing around this? If not, should we add some?

**Comment by rschalo** [comment]
Yes I'll look at adding an integration test, still thinking about how we could model this.

**Comment by rschalo** [comment]
Discussed testing offline - moving ahead without for now.

**Comment by applike-ss** [comment]
This will make the aws-load-balancer-controller unable to reach the EC2 Metadata service, which in turn requires to specify the region and vpcId.

Was this taken into consideration?

**Pull request merged**
