### PR TITLE
ci: Increase max retry for the sweeper

### PR DESCRIPTION
**Pull request by engedaam**
Fixes #N/A 

**Description**
- We are experiencing throttling in our [sweeper](https://github.com/aws/karpenter-provider-aws/actions/runs/9564694974/job/26366008036) and will need to increase the default retry attempt 
```
operation error IAM: ListInstanceProfileTags, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: f4676348-05c7-47e8-aae5-6402e1ce5040,
```
- Since the retry strategy is exponential backoff, increasing the number of retry attempts from 3 to 10 to make sure that call will be spread out exponentially and increase the likelihood of call succeeding 

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rschalo** [comment]
What's the schedule for the sweeper again? Why 10 as the max default?

**Comment by engedaam** [comment]
The schedule the sweeper is every 12 hours. Giving 10 max retries allows us to attempt to get instance profiles tags with more spread of a delay to allow us to refile the read tokens. The schedule will be as such: 

0 | 0.000 |
1 | 0.030 |
2 | 0.060 |
3 | 0.090 |
4 | 0.120 |
5 | 0.150 |
6 | 0.180 |
7 | 0.210 |
8 | 0.240 |
9 | 0.270 |

**Comment by jmdeal** [comment]
Is the backoff linear or exponential? I'm reading the schedule you wrote as "incremented by 30ms each time" rather than an exponential backoff. I don't think it matters too much, but wanted to clarify before I approve. Otherwise looks good.

**Comment by engedaam** [comment]
I fixed the comment, the backoff is exponential

**Review by jmdeal — APPROVED** [review]
LGTM 🚀

**Pull request merged**
