### PR TITLE
test: add budgets replacement tests

### PR DESCRIPTION
**Pull request by njtran**
Fixes #N/A 

**Description**
Adds tests to test concurrent disruption replacements

**How was this change tested?**
make e2etests

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by njtran — COMMENTED** [review]
/karpenter snapshot

**Review by njtran — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Pull request merged**
