### PR TITLE
fix: Add truncating back to cloudprovider, considering minValues

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #N/A 

**Description**

This change adds an `instanceTypes.Truncate()` call back to the CloudProvider on 60 instance types. This will make no difference in the standard codepath since we already truncate in the scheduler but matters for cases when users launch standalone NodeClaims.

This should fix all failures in the NodeClaim suite in our [VersionCompatability suite](https://github.com/aws/karpenter-provider-aws/actions/workflows/e2e-version-compatibility-trigger.yaml) that run in `eu-west-1`. This test suite was failing consistently because we were sending too many instance types to EC2 Fleet, causing an error for too large of a response body to come back.

**How was this change tested?**

`make presubmit`
`/karpenter snapshot`
Running the NodeClaim suite on a local cluster in `eu-west-1`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — APPROVED** [review]
LGTM 🚀

**Pull request merged**
