### PR TITLE
docs: grafana dashboard - capacity metric name from provisioner to nodepool.

### PR DESCRIPTION
**Pull request by eTimS**
Hello!

small change to the capacity dashboard:
rename capacity metric name from provisioner to nodepool  

I did not understood the transform data that is done in this dashboard, I left it untouched.
On our metrics, we have a cluster label that is used on the join by field (not sure if it is what is expected here).

Fixes #N/A 

**Description**

**How was this change tested?**
Dashboard imported as is

**Does this change impact docs?**
- [x] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by eTimS** [comment]
I just noticed  that a lot more needs to be changed in the dashboard, making this PR irrelevant for now

**Comment by eTimS** [comment]
with commit [725dc1e](https://github.com/aws/karpenter-provider-aws/pull/5553/commits/725dc1e1852589b24e3447f1430b5a6b3a3575ae) it should be fully renamed (I tested again importing the dashboard as is)

**Comment by jonathan-innis** [comment]
Looks like a potential duplicate of #5546

**Comment by jonathan-innis** [comment]
I'm going to close this one for now. If you think there are any changes that need to go into #5546, you can go ahead and comment on that PR.

**Pull request closed without merging**
