### PR TITLE
chore: Add support for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by AhmadMasry**
Fixes [5572](https://github.com/aws/karpenter-provider-aws/issues/5572)

**Description**

- The Ubuntu EKS optimized AMI started to support 22.04 for Kubernetes 1.29+, to make sure that 20.04 and 22.04 can be used, two new `amiFamily` which are `Ubuntu2004`, `Ubuntu2204` have been introduced.
- `Ubuntu2204` `amiFamily` can only be used for Kubernetes 1.29+.
- For backward compatibility, `amiFamily` `Ubuntu` is equivalent to `Ubuntu2004`.
- This change can be useful if the upcoming Ubuntu 24.04 will be supported as an Ubuntu EKS optimized AMI and the older versions will be supported until the end of [LTS standard security maintenance for Ubuntu Main](https://ubuntu.com/about/release-cycle#ubuntu).

**How was this change tested?**
I tested it on an EKS cluster with version 1.29 using `Ubuntu`, `Ubuntu2004` and `Ubuntu2204` and all have worked and provisioned.

**Does this change impact docs?**
- [x] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by AhmadMasry** [comment]
Hi @engedaam 
Can you have a look at this PR, and if you have any notes or comments please feel free to provide them so I can do the needed changed.
Thanks

**Comment by jonathan-innis** [comment]
> Can you have a look at this PR, and if you have any notes or comments please feel free to provide them so I can do the needed changed

I'll let @jmdeal to add some additional thoughts here, but there's still some ongoing discussion in #5572. I wonder if we can push for getting SSM support in (https://github.com/aws/karpenter-provider-aws/issues/3657) and userData templating (https://github.com/aws/karpenter-provider-aws/issues/5134) if that would be a better path forward than continuing to add more support for the Ubuntu AMIFamily as they continue to bump their major version.

**Comment by AhmadMasry** [comment]
Test cases have been fixed.

**Comment by AhmadMasry** [comment]
Thank you @jmdeal for your feedback.
I think supporting 22.04 can be a short-term fix, until the SSM parameters and user data templating are supported.
I sent to Canonical and it seems that supporting 24.04 EKS AMIs is not on their roadmap yet, so I do not think the support of 24.04 will be needed in the short term and until the SSM parameters and user data templating are supported, This PR can utilized to use the newer ubuntu images.

**Comment by AhmadMasry** [comment]
Hi @jonathan-innis @jmdeal 
So, do you want me to close the PR? or do you want to go with my suggestion to support 22.04 until SSM parameters and user data templating are supported?
Thank you for your efforts.

**Comment by jmdeal** [comment]
Given that we're currently planning on dropping support for Ubuntu as a managed AMI family at v1 ([v1 Roadmap Proposal](https://github.com/kubernetes-sigs/karpenter/pull/1222)), we don't want to signal future support at this point. Ubuntu 22.04 still be used with the Ubuntu AMI family and AMI selector terms for users migrating to k8s 1.30 once Canonical releases 1.30 EKS optimized AMIs.

**Pull request closed without merging**
